export const ROUTES = {
  home: "/",
  join: "/join",
  signIn: "/sign-in",
  signUp: "/sign-up/1",
  signUpStep2:"/sign-up/2",
  artistSignIn: "/artist-signin",
  artistSignUp: "/artist-signup/1",
  artistSignUp2: "/artist-signup/2",
  forgotPassword:"/forgot-password",
  aboutus: "/aboutus",
  artists: "/artists",
  projects: "/projects",
  nfts: "/nfts",
  nftOnSale: "/nft-on-sale",
  auctions: "/auctions",
  nftProject: "/project/[projectId]",
  project:"/project/",
  artistProfile: "/artist/",
  auction: "/auction/",
  payment: "/payment",
  moonpay: "/moonpay",
  account: "/my-account",
  artistAccount: "/artist-account",
  checkout: "/checkout",
  transactionSuccess: "/transaction/success",
  transactionFailure: "/transaction/failure",
  projectRegister: "/project/register",
  projectWaiting: "/project/waiting/[projectId]",
  notFound: "/404",
};
